DROP TABLE IF EXISTS VEHICLE_PRICE;
DROP TABLE IF EXISTS VEHICLE_FEATURE_MAPPER;
DROP TABLE IF EXISTS VEHICLE_FEATURE;
DROP TABLE IF EXISTS VEHICLE_DETAILS;

CREATE TABLE VEHICLE_DETAILS (
  vehicle_id INT PRIMARY KEY,
  make VARCHAR(50) NOT NULL,
  model VARCHAR(50) NOT NULL,
  model_year int NOT NULL,
  body_style VARCHAR(50) NOT NULL,
  engine VARCHAR(50) NOT NULL,
  drive_type VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL,
  mpg DECIMAL(10,2) NOT NULL
);

CREATE TABLE VEHICLE_FEATURE (
  feature_id INT AUTO_INCREMENT  PRIMARY KEY,
  feature_name VARCHAR(50) NOT NULL,
  feature_type VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICLE_FEATURE_MAPPER (
  vehicle_id INT NOT NULL,
  feature_id INT NOT NULL,
  FOREIGN KEY (vehicle_id) REFERENCES VEHICLE_DETAILS(vehicle_id),
  FOREIGN KEY (feature_id) REFERENCES VEHICLE_FEATURE(feature_id)
);

CREATE TABLE VEHICLE_PRICE (
  vehicle_id INT NOT NULL,
  msrp DECIMAL(10,2) NOT NULL,
  savings DECIMAL(10,2) NOT NULL,
  final_price DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (vehicle_id) REFERENCES VEHICLE_DETAILS(vehicle_id)
);